### Registration input (object)
- name: `Jose Fonseca`(string, required) - The name of the user
- email: `email@example.com` (string, required) - The email of the user
- password: `Password123**` (string, required) - The password of the user
- password_confirmation: `123456789` (string, required) - The password confirmation of the user
