## Error 404 (object)
- message: `Not found` (string)

## Error 400 (object)
- message: `Bad Request` (string)

## Error 403 (object)
- message: `Forbidden` (string)

## Error 401 (object)
- message: `Unauthorized` (string)

## Error 405 (object)
- message: `Method Not Allowed` (string)

## Error 422 (object)
- message: `Validation error` (string)
- errors (array) `Array of errors present in the validation`