## Error 404 (object)
- message: `404 Not found` (string)
- status_code: 404 (number) `status code number`

## Error 400 (object)
- message: `Bad Request` (string)
- status_code: 400 (number) `status code number`

## Error 403 (object)
- message: `Forbidden` (string)
- status_code: 403 (number) `status code number`

## Error 401 (object)
- message: `Unauthenticated.` (string)
- status_code: 401 (number) `status code number`

## Error 405 (object)
- message: `Method Not Allowed` (string)
- status_code: 405 (number) `status code number`

## Error 422 (object)
- message: `Validation error` (string)
- errors (array) `Array of errors present in the validation`
- status_code: 422 (number) `status code number`