## Role Minimal (object)
- type: `roles` (string)
- id: `01020af0-44b5-11e7-8001-41a6bfe4ef85` (string)

## Role Object (object)
- type: `roles` (string)
- id: `01020af0-44b5-11e7-8001-41a6bfe4ef85` (string)
- attributes
    - name: `Guest` (string)
    - created_at: `2017-02-09T03:28:32+00:00` (string)
    - updated_at: `2017-02-09T03:28:32+00:00` (string)
- links
    - self: `http://laravelapi.dev/api/roles/01020af0-44b5-11e7-8001-41a6bfe4ef85`