## User Object (object)
- id: `d4d42ea0-ee77-11e6-b823-6d63c6504afc` (string)
- name: `Jhon Doe` (string)
- email: `email@example.com` (string)
- created_at: `2017-02-09T03:28:32+00:00` (string)
- updated_at: `2017-02-09T03:28:32+00:00` (string)
- roles
    - data (array)
        - (Role Object)
        - (Role Object)

## User Create (object)
- name: `Jhon Doe` (string, required)
- email: `email@example.com` (string, required)
- password: `123456789` (string, required)
- password_confirmation: `123456789` (string, required)
- roles (array)
    - `d4d42ea0-ee77-11e6-b823-6d63c6504afc` (string) Role ID
    - `d4d42ea0-ee77-11e6-b823-6d63c6504afc` (string) Role ID
    - `d4d42ea0-ee77-11e6-b823-6d63c6504afc` (string) Role ID

## User Update (object)
- name: `Jhon Doe` (string, optional)

## User Update Full (object)
- name: `Jhon Doe` (string, required)
- email: `email@example.com` (string, required)

## User Pagination (object)
- total: 30 (number)
- count: 20 (number)
- per_page: 20 (number)
- current_page: 1 (number)
- total_pages: 2 (number)
- links
    - previous: `http://laravelapi.dev/api/users?page=1` (string)
    - next: `http://laravelapi.dev/api/users?page=2` (string)
    - last: `http://laravelapi.dev/api/users?page=2` (string)
    
## User Update Password (object)
- current_password: `12345` (string, required)
- password: `123456789qq` (string, required)
- password_confirmation: `123456789qq` (string, required)