FORMAT: 1A
HOST: https://example.com

# Laravel API
Welcome to the Starter Kit API, here you will find all the information related to the endpoints available.

## Authentication

The API uses [oAuth2](https://oauth.net/2/) for authentication, this means that all API calls should contain and authorization that looks like this

```
Authorization: Bearer API_KEY_HERE
```

Please see the Authentication documentation to know how to get an access token.

## Headers

Make sure you have the following content type headers are set on every request:

```http
Accept: application/vnd.api.v1+json
Content-Type: application/json
```

## Errors

The API uses conventional HTTP response codes to indicate the success or failure of an API request. The table below contains a summary of the typical response codes:

| Code | Description                                                            |
|------|------------------------------------------------------------------------|
| 200  | Everything is ok.                                                      |
| 400  | Valid data was given but the request has failed.                       |
| 401  | No valid API Key was given.                                            |
| 404  | The request resource could not be found.                               |
| 405  | The method is not implemented                                          |
| 422  | The payload has missing required parameters or invalid data was given. |
| 429  | Too many attempts.                                                     |
| 500  | Request failed due to an internal error.                               |
| 503  | API is offline for maintenance.                                        |

# Data Structures

<!-- include(dataStructures/errors.apib) -->
<!-- include(dataStructures/users.apib) -->
<!-- include(dataStructures/roles.apib) -->
<!-- include(dataStructures/permissions.apib) -->
<!-- include(dataStructures/assets.apib) -->

<!-- include(routes/users.apib) -->
<!-- include(routes/assets.apib) -->